
window.onload = () => {
    const paragraphs = [
        "We here at CompanyCo think we know that it is better to upgrade intuitively than to utilize virtually. Your budget for optimizing should be at least three times your budget for extending. Your budget for strategizing should be at least twice your budget for utilizing. A company that can incubate elegantly will (at some indefinite point of time) be able to implement easily. Think co-branded. Without user interfaces, you will lack raw bandwidth. Our technology takes the best features of HTTP and DOM. We apply the proverb \"Like father like son\" not only to our C2C but our capability to reintermediate. Without adequate portals, power shifts are forced to become seamless. We think that most transparent web portals use far too much XForms, and not enough Unix.",
        "CompanyCo has revolutionized the theory of implementation. We apply the proverb \"When the cat's away, the mice will play\" not only to our seamless compliance but our capability to whiteboard. Without appropriate eyeballs, scalable versioning reports are forced to become leading-edge. We have come to know that if you transform holistically then you may also incubate nano-globally. If you integrate compellingly, you may have to reinvent macro-iteravely. We realize that if you reinvent transparently then you may also incentivize strategically. What does the commonly-used term \"viral\" really mean? We will deploy the industry jargon \"blog-based\". Without cross-media iteration, you will lack bandwidth. We apply the proverb \"Grass doesn't grow on a racetrack\" not only to our synergies but our power to incentivize.",
        "At CompanyCo, we realize how to benchmark interactively. The metrics for convergence are more well-understood if they are not C2C2C. We will whiteboard the ability of users to aggregate. We will incubate the ability of user interfaces to strategize. The capacity to harness globally leads to the power to empower iteravely. A company that can enable faithfully will (eventually) be able to iterate courageously. What do we orchestrate? Anything and everything, regardless of obscureness! Your budget for exploiting should be at least one-half of your budget for revolutionizing. We have proven we know that if you enable extensibly then you may also redefine intra-extensibly. Our technology takes the best features of XForms and Java. Is it more important for something to be B2C or to be clicks-and-mortar? Think super-super-virally-distributed.",
        "CompanyCo is the industry leader of next-generation paradigms. Without preplanned accounting reports, relationships are forced to become customized, synergistic. Your budget for whiteboarding should be at least one-half of your budget for deploying. What does the term \"holistic\" really mean? Without iteration, you will lack reporting. We often deliver six-sigma versioning. That is a remarkable achievement considering this year's financial state of things! Think nano-short-term, B2B2C. We will reinvent the power of users to strategize. Our feature set is unmatched in the industry, but our viral eyeballs and non-complex use is always considered an amazing achievement. Quick: do you have a dynamic plan of action for coping with new user interfaces?",
        "We here at CompanyCo have come to know that it is better to iterate interactively than to whiteboard wirelessly. We frequently utilize distributed mission-critical, transparent systems. That is a terrific achievement taking into account the current fiscal year's financial state of things! We realize that it is better to whiteboard intra-extensibly than to empower super-intuitively. What does it really mean to integrate \"interactively\"? The ability to recontextualize intuitively leads to the ability to reintermediate ultra-super-micro-ultra-micro-magnetically. What do we streamline? Anything and everything, regardless of standing! Our technology takes the best aspects of RDF and AJAX. A company that can e-enable faithfully will (at some indefinite point in the future) be able to drive easily. Quick: do you have a B2B2C, 1000/60/60/24/7/365 plan of action for handling new project management reports? A company that can extend easily will (eventually) be able to incubate courageously. Think dot-com.",
        "CompanyCo practically invented the term \"CAE\". The C2C factor is global. Our technology takes the best aspects of PNG and JavaScript. It comes off as puzzling, but it's accurate! Think intuitive. We will matrix the term \"end-to-end\". If you transform transparently, you may have to drive wirelessly. We pride ourselves not only on our virally-distributed feature set, but our user-proof administration and user-proof operation. Imagine a combination of ASP and OWL. Our technology takes the best aspects of FOAF and CSS. Without preplanned infomediaries, paradigms are forced to become infinitely reconfigurable. Do you have a plan of action to become robust?",
        "At CompanyCo, we have proven we know how to incubate seamlessly. We apply the proverb \"A barking dog never bites\" not only to our solutions but our ability to incentivize. Our feature set is unparalleled in the industry, but our global solutions and newbie-proof configuration is constantly considered a terrific achievement. Without 24/7/365, open-source customized reporting, you will lack architectures. We pride ourselves not only on our world-class feature set, but our non-complex administration and simple use. The relationships factor can be summed up in one word: cross-media. Think ultra-reconfigurable. What do we monetize? Anything and everything, regardless of obscurity! The CAD factor is co-branded. Quick: do you have a integrated, 1000/60/60/24/7/365 scheme for monitoring emerging angel investors? It comes off as alarming, but it's true! If you target efficiently, you may have to morph extensibly."
    ]

    document.getElementById('about-1').innerHTML = paragraphs[Math.floor(Math.random() * paragraphs.length)];
    document.getElementById('about-2').innerHTML = paragraphs[Math.floor(Math.random() * paragraphs.length)];

    const thingsWeDo = [
        "We think we know that it is better to strategize magnetically than to cultivate transparently. The ability to evolve efficiently leads to the ability to utilize magnetically.",
        "Think mega-end-to-end. The metrics for ultra-60/24/7/365 iteration are more well-understood if they are not affiliate-based.",
        "We will monetize the aptitude of angel investors to synthesize. We will exploit the capacity of project management management metrics to scale.",
        "A company that can redefine courageously will (at some point) be able to empower easily. The super-short-term initiatives factor can be summed up in one word: visionary."
    ]

    document.getElementById('wwd-text').innerHTML = thingsWeDo[Math.floor(Math.random() * thingsWeDo.length)];
}